language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t jan.psota/docker-react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true jan.psota/docker-react:latest npm run test -- -- coverage 