FROM node:alpine

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

COPY --chown=node:node ./.babelrc ./
 
RUN npm install
COPY --chown=node:node ./ ./
 
EXPOSE 80

CMD ["npm",  "start"]


